#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo '🏗️👷 linting project'

# Check ESLint Standards
npm run eslint:fix ||
(
        echo '😤🏀👋😤 Get that weak s**t out of here! 😤🏀👋😤 
                ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
        false; 
)

npm run stylelint:fix ||
(
   echo '❌👷🔨❌ Better call Bob... Because your style bullshit ❌👷🔨❌
   '
   false;
)
#
# If everything passes... Now we can commit
echo '✅✅✅✅ You win this time... I am committing this now. ✅✅✅✅'
